-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgofylYauCWtirvKhS
R2J6h0MYQXTc/NFOvQBjeFAH+OygCgYIKoZIzj0DAQehRANCAAQ/WFbRaHyv9q60
/2aCkMmiIwCTcsONMrSnWFsuJfrryygxegfD056hAWjngon1xDu2N+W4UG33+Pn8
aa3+kwki
-----END PRIVATE KEY-----